name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t maridoroshuk/weather
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password stdin
    - run: docker push maridoroshuk/weather
